#!/bin/bash

current_scheme=$(gsettings get org.gnome.shell.ubuntu color-scheme)

if [[ $current_scheme == "'prefer-dark'" ]]; then
  gsettings set org.gnome.shell.ubuntu color-scheme prefer-light
  gsettings set org.gnome.desktop.interface gtk-theme Yaru
  gsettings set org.gnome.desktop.interface color-scheme prefer-light
  
  HX_CONFIG_FILE="$HOME/.config/helix/config.toml"
  HX_DARK_THEME="gruvbox_dark_soft"
  HX_LIGHT_THEME="gruvbox_light_soft"
  sed -i "s|$HX_DARK_THEME|$HX_LIGHT_THEME|g" "$HX_CONFIG_FILE"
  
  TTY_CONFIG="$HOME/.config/alacritty/alacritty.toml"
  TTY_DARK_THEME='"~/.config/alacritty/themes/themes/gruvbox_dark.toml"'
  TTY_LIGHT_THEME='"~/.config/alacritty/themes/themes/gruvbox_light.toml"'
  sed -i "s|$TTY_DARK_THEME|$TTY_LIGHT_THEME|g" "$TTY_CONFIG"
else
  gsettings set org.gnome.shell.ubuntu color-scheme prefer-dark
  gsettings set org.gnome.desktop.interface gtk-theme Yaru-sage-dark
  gsettings set org.gnome.desktop.interface color-scheme prefer-dark 
  
  # tty
  HX_CONFIG_FILE="$HOME/.config/helix/config.toml"
  HX_DARK_THEME="gruvbox_dark_soft"
  HX_LIGHT_THEME="gruvbox_light_soft"
  sed -i "s|$HX_LIGHT_THEME|$HX_DARK_THEME|g" "$HX_CONFIG_FILE"
  
  TTY_CONFIG="$HOME/.config/alacritty/alacritty.toml"
  TTY_DARK_THEME='"~/.config/alacritty/themes/themes/gruvbox_dark.toml"'
  TTY_LIGHT_THEME='"~/.config/alacritty/themes/themes/gruvbox_light.toml"'
  sed -i "s|$TTY_LIGHT_THEME|$TTY_DARK_THEME|g" "$TTY_CONFIG"
fi
